/**
 * core/stacklit-bridge.ts
 *
 * Reads stacklit.json and provides token-health-aware codebase context
 * to both agents through the API.
 *
 * Key design decisions:
 * - Stacklit is read-only from Duostack's perspective. We never write
 *   to stacklit.json — Stacklit's git hook manages it.
 * - Three read modes based on token health:
 *   full_index  → parse and return full stacklit.json (~4k tokens)
 *   derive_map  → generate a compact summary (~250 tokens)
 *   mcp_query   → answer a specific module question (cheapest per query)
 *   skip        → return nothing (final_flush mode)
 * - The derive_map is generated by Duostack from stacklit.json, not by
 *   running the stacklit CLI. This makes it available even if stacklit
 *   isn't installed globally.
 * - Results are cached in memory with a 5-minute TTL. The git hook
 *   regenerates stacklit.json on commits, so we re-read after TTL.
 */

import fs from "node:fs";
import fsPromises from "node:fs/promises";
import type { DuostackConfig } from "./config.js";

// ─── Types ────────────────────────────────────────────────────────────────────

export type StacklitReadMode =
  | "full_index"
  | "derive_map"
  | "mcp_query"
  | "skip";

export interface StacklitModule {
  purpose: string;
  files: number;
  lines: number;
  exports: string[];
  depends_on: string[];
  activity: "high" | "medium" | "low";
}

export interface StacklitIndex {
  modules: Record<string, StacklitModule>;
  hints: {
    add_feature?: string;
    test_command?: string;
    [key: string]: string | undefined;
  };
  framework?: string;
  languages?: string[];
  entrypoint?: string;
  total_files?: number;
  total_lines?: number;
}

export interface DeriveMap {
  summary: string;          // one-line project summary
  entry: string;            // entrypoint file
  testCommand: string;      // how to run tests
  moduleCount: number;
  totalLines: number;
  hotModules: string[];     // high-activity modules
  modules: Array<{
    path: string;
    purpose: string;
    exports: string[];
    dependsOn: string[];
  }>;
}

export interface ModuleQueryResult {
  modulePath: string;
  found: boolean;
  purpose: string | null;
  exports: string[];
  dependsOn: string[];
  dependedOnBy: string[];
  files: number;
  lines: number;
}

// ─── Stacklit bridge ──────────────────────────────────────────────────────────

export class StacklitBridge {
  private config: DuostackConfig;
  private cache: { index: StacklitIndex; loadedAt: number } | null = null;
  private readonly cacheTtlMs = 5 * 60 * 1000; // 5 minutes

  constructor(config: DuostackConfig) {
    this.config = config;
  }

  // ─── Availability ──────────────────────────────────────────────────────────

  isAvailable(): boolean {
    return this.config.stacklit.enabled &&
      fs.existsSync(this.config.stacklit.jsonPath);
  }

  // ─── Read full index ───────────────────────────────────────────────────────

  /**
   * Read the full stacklit.json index.
   * Used at session start when token health is normal.
   * ~4k tokens for most projects.
   */
  async readFullIndex(): Promise<StacklitIndex | null> {
    if (!this.isAvailable()) return null;

    const index = await this.loadIndex();
    return index;
  }

  // ─── Generate derive map ───────────────────────────────────────────────────

  /**
   * Generate a compact derive map from stacklit.json.
   * Used when token health is batching or triage.
   * ~250 tokens for most projects.
   *
   * Mirrors what `stacklit derive` produces but generated in-process
   * so it works without the stacklit CLI being on PATH.
   */
  async generateDeriveMap(): Promise<DeriveMap | null> {
    if (!this.isAvailable()) return null;

    const index = await this.loadIndex();
    if (!index) return null;

    const modules = Object.entries(index.modules ?? {});
    const totalLines = modules.reduce(
      (sum, [, m]) => sum + (m.lines ?? 0),
      0
    );

    // Hot modules — high activity, sort by lines descending
    const hotModules = modules
      .filter(([, m]) => m.activity === "high")
      .sort(([, a], [, b]) => (b.lines ?? 0) - (a.lines ?? 0))
      .slice(0, 5)
      .map(([path]) => path);

    // Build compact module list
    const compactModules = modules
      .slice(0, 20) // cap at 20 for token budget
      .map(([modPath, m]) => ({
        path: modPath,
        purpose: m.purpose ?? "",
        exports: (m.exports ?? []).slice(0, 5), // top 5 exports
        dependsOn: m.depends_on ?? [],
      }));

    const summary = [
      index.framework ?? "unknown framework",
      `${index.languages?.join("/") ?? "unknown lang"}`,
      `${modules.length} modules`,
      `${totalLines.toLocaleString()} lines`,
    ].join(" | ");

    return {
      summary,
      entry: index.entrypoint ?? "unknown",
      testCommand: index.hints?.test_command ?? "unknown",
      moduleCount: modules.length,
      totalLines,
      hotModules,
      modules: compactModules,
    };
  }

  // ─── Module query ──────────────────────────────────────────────────────────

  /**
   * Answer a specific module question.
   * Used when token health is normal and the agent needs targeted info.
   * Much cheaper than reading the full index if you only need one module.
   *
   * Supports fuzzy matching — "auth" matches "src/auth", "src/auth/index.ts", etc.
   */
  async queryModule(query: string): Promise<ModuleQueryResult> {
    const notFound: ModuleQueryResult = {
      modulePath: query,
      found: false,
      purpose: null,
      exports: [],
      dependsOn: [],
      dependedOnBy: [],
      files: 0,
      lines: 0,
    };

    if (!this.isAvailable()) return notFound;

    const index = await this.loadIndex();
    if (!index) return notFound;

    // Find matching module (exact then fuzzy)
    const modules = index.modules ?? {};
    let modulePath = Object.keys(modules).find(
      (k) => k === query || k.toLowerCase() === query.toLowerCase()
    );

    if (!modulePath) {
      // Fuzzy: contains query
      modulePath = Object.keys(modules).find((k) =>
        k.toLowerCase().includes(query.toLowerCase())
      );
    }

    if (!modulePath) return notFound;

    const module = modules[modulePath]!;

    // Find modules that depend on this one
    const dependedOnBy = Object.entries(modules)
      .filter(([, m]) => m.depends_on?.includes(modulePath!))
      .map(([path]) => path);

    return {
      modulePath,
      found: true,
      purpose: module.purpose ?? null,
      exports: module.exports ?? [],
      dependsOn: module.depends_on ?? [],
      dependedOnBy,
      files: module.files ?? 0,
      lines: module.lines ?? 0,
    };
  }

  // ─── Token-health-aware read ───────────────────────────────────────────────

  /**
   * Read codebase context appropriate for the given token health level.
   * This is the main entry point for agents — they call this and get
   * the right amount of context without having to decide themselves.
   */
  async readForTokenHealth(
    health: string,
    moduleQuery?: string
  ): Promise<{
    mode: StacklitReadMode;
    data: StacklitIndex | DeriveMap | ModuleQueryResult | null;
    estimatedTokens: number;
  }> {
    if (!this.isAvailable()) {
      return { mode: "skip", data: null, estimatedTokens: 0 };
    }

    switch (health) {
      case "normal": {
        if (moduleQuery) {
          const result = await this.queryModule(moduleQuery);
          return {
            mode: "mcp_query",
            data: result,
            estimatedTokens: 150,
          };
        }
        // Default to derive map even in normal mode for initial orientation
        // Full index is available via direct API call when needed
        const derive = await this.generateDeriveMap();
        return {
          mode: "derive_map",
          data: derive,
          estimatedTokens: 250,
        };
      }

      case "batching":
      case "triage": {
        const derive = await this.generateDeriveMap();
        return {
          mode: "derive_map",
          data: derive,
          estimatedTokens: 250,
        };
      }

      case "final_flush":
      case "exhausted":
        return { mode: "skip", data: null, estimatedTokens: 0 };

      default: {
        const full = await this.readFullIndex();
        return {
          mode: "full_index",
          data: full,
          estimatedTokens: this.config.stacklit.fullIndexTokenBudget,
        };
      }
    }
  }

  // ─── Dependencies ──────────────────────────────────────────────────────────

  /**
   * Get the full dependency graph for a module.
   * Useful for Claude when planning refactors — understand blast radius.
   */
  async getDependencyGraph(
    modulePath: string,
    depth: number = 2
  ): Promise<Record<string, string[]>> {
    if (!this.isAvailable()) return {};

    const index = await this.loadIndex();
    if (!index) return {};

    const graph: Record<string, string[]> = {};
    const visited = new Set<string>();

    const traverse = (path: string, currentDepth: number) => {
      if (currentDepth === 0 || visited.has(path)) return;
      visited.add(path);

      const module = index.modules?.[path];
      if (!module) return;

      graph[path] = module.depends_on ?? [];

      for (const dep of module.depends_on ?? []) {
        traverse(dep, currentDepth - 1);
      }
    };

    traverse(modulePath, depth);
    return graph;
  }

  // ─── Stats ─────────────────────────────────────────────────────────────────

  async getStats(): Promise<{
    available: boolean;
    path: string;
    moduleCount: number;
    totalLines: number;
    lastModified: string | null;
    cacheAge: number | null;
  }> {
    if (!this.isAvailable()) {
      return {
        available: false,
        path: this.config.stacklit.jsonPath,
        moduleCount: 0,
        totalLines: 0,
        lastModified: null,
        cacheAge: null,
      };
    }

    const index = await this.loadIndex();
    const stat = await fsPromises
      .stat(this.config.stacklit.jsonPath)
      .catch(() => null);

    const modules = Object.values(index?.modules ?? {});
    const totalLines = modules.reduce((sum, m) => sum + (m.lines ?? 0), 0);

    return {
      available: true,
      path: this.config.stacklit.jsonPath,
      moduleCount: modules.length,
      totalLines,
      lastModified: stat?.mtime.toISOString() ?? null,
      cacheAge: this.cache
        ? Date.now() - this.cache.loadedAt
        : null,
    };
  }

  // ─── Private helpers ───────────────────────────────────────────────────────

  private async loadIndex(): Promise<StacklitIndex | null> {
    // Return cached if fresh
    if (this.cache && Date.now() - this.cache.loadedAt < this.cacheTtlMs) {
      return this.cache.index;
    }

    try {
      const raw = await fsPromises.readFile(
        this.config.stacklit.jsonPath,
        "utf-8"
      );
      const index = JSON.parse(raw) as StacklitIndex;
      this.cache = { index, loadedAt: Date.now() };
      return index;
    } catch (err) {
      console.error(`[stacklit-bridge] failed to read stacklit.json: ${err}`);
      return null;
    }
  }

  invalidateCache(): void {
    this.cache = null;
  }
}

// ─── Factory ──────────────────────────────────────────────────────────────────

export function createStacklitBridge(config: DuostackConfig): StacklitBridge {
  return new StacklitBridge(config);
}
